### ISSUE TITLE
If I wanted to generate this myself, what would the commands be?

### ISSUE THREAD

**Issue by bsullins** [tableau-mkt/github-data-connector#10]
I'm confused by the generator. I have it all setup, and am not clear where to enter the actual API endpoint or if that is supposed to be an option during generation.

**Comment by Etroid** [comment]
Since this data connector is specifically made for Github API calls, its API endpoint is currently set by default to "https://api.github.com/".  Perhaps this issue was meant for https://github.com/tableau-mkt/generator-web-data-connector instead?
