### ISSUE TITLE
Support for traffic stats from GitHub

### ISSUE THREAD

**Issue by jsevedge** [tableau-mkt/github-data-connector#12]
Would it be possible for you to add support for traffic stats to this web data connector?  It will save me the time to try and implement it myself.  Basically the data formatting is all that needs to be accounted for as when I attempt it it succeeds in the connector but no rows/columns get created in tableau.

For example below url returns a json list of referrers and a couple items such as count, referrer, etc..
repos/:org/:repo/traffic/popular/referrers

API Doc - There is only a couple of API endpoints under traffic, but they are useful to report on.
https://developer.github.com/v3/repos/traffic/

**Comment by Etroid** [comment]
There is definitely some useful data in there! I am currently beta testing a new version of the connector using the 2.0 Tableau WDC API and can probably plug this feature in there before its upcoming release.

**Comment by jsevedge** [comment]
Awesome, I would really appreciate it and I think others would find it useful as well, not just my company.  Let me know if i can help in any way(testing or otherwise)...

**Comment by Etroid** [comment]
You should be able to test the new Traffic functionality by using the new [beta connector](https://github-web-data-connector-dev.herokuapp.com/github/)

### 1. Open Tableau, navigate to web data connector and enter the following url:
https://github-web-data-connector-dev.herokuapp.com/github/

### 2. Authenticate with your GH account.
![screen shot 2017-04-03 at 10 46 21 am](https://cloud.githubusercontent.com/assets/8611594/24622793/1fb77250-185b-11e7-8ba2-2cdc6a4985bb.png)

### 3. Choose traffic and insert a valid url such as provided in the examples.
![screen shot 2017-04-03 at 8 28 26 am](https://cloud.githubusercontent.com/assets/8611594/24622827/3d24face-185b-11e7-825e-e432e2719c3f.png)

### 4. Click get Data and choose your table and/or select the default connection to obtain all traffic data.
![screen shot 2017-04-03 at 8 28 41 am](https://cloud.githubusercontent.com/assets/8611594/24622849/529f2032-185b-11e7-9355-e0f301fd7826.png)

**Comment by jsevedge** [comment]
Awesome Etroid, I just tested and was able to pull in the traffic stats.. I will play around with this some more but looks good to go to me initially!

Thanks,
