### ISSUE TITLE
Incremental Refresh

### ISSUE THREAD

**Issue by jsevedge** [tableau-mkt/github-data-connector#13]
Hello, was interested in if this WDC is planned to support incremental refresh?  I am unable to get it to work, although I could be missing a step somewhere.  I understand there is some client-side steps to indicate incremental refresh(not appearing for me) as well as some WDC items specifically as laid out below.

https://tableau.github.io/webdataconnector/docs/wdc_incremental_refresh

Much appreciated,

**Comment by jsevedge** [comment]
As additional information, what I am trying to get at is if, for example "traffic stats", data in GitHub is available for the last 14 days, the WDC if doing a full extract daily will only contain the last 14 days of data and lose anything older, and was hoping/wondering if in general using incremental refresh in the WDC would solve for that?  In my research i may have missed an obvious answer but figured asking at the source of the GitHub WDC if this behaviour is expected?

**Comment by Etroid** [comment]
Hey @jsevedge 

I did not implement it because most scenarios in Github do not benefit from incremental change. Quick example, issues and pull requests can be updated and do not generate new records for each change. Tableau's incremental change is built with the idea in mind that changes are accounted for in new records and you only need to pull in the deltas (i.e. latest records since your last refresh)/

Traffic stats could maybe benefit from this feature though. Every time you refresh you get a 14-day snapshot of traffic in a set of records. This does not mean however that you will automatically get all the latest changes since the last time you refreshed. Github does not let you get historical stats, and so if you haven't refreshed in 14 days you would be missing data.

Let me know if this is what you are looking for and I can start scoping the work. 

Cheers

**Comment by jsevedge** [comment]
Hey @Etroid 
Thanks for the quick response, so maybe I am slightly confusing the both of us.  The issue currently is i dont have the traffic stats posted to Tableau server(need to get it whitelisted by the admin) and so am playing only in Tableau desktop.  So when i complete the first extract of the traffic stats using the WDC as a new connection i get the last 14 days(as expected), but then if i wait a day(or week) i dont have an option to refresh that connection in tableau desktop and the data gets stale(if I try to refresh the extract stays the same with the original 14 days), i have to add a new connection to get it to work and so of course then only get the last 14 days from that point in time.  So am i supposed to be able to refresh the extract in Tableau desktop and retain older then 14 days(if previously extracted), and is the same for Tableau server the case(once i am able to test when the WDC is whitelisted and set up a extract schedule)?   Hopefully that clarifies it as the actual results i am seeing vs. what i would like to happen.

**Comment by Etroid** [comment]
Hey @jsevedge 

That makes sense. Let me hack away on a quick example to see if this is doable.

**Comment by jsevedge** [comment]
@Etroid 
Awesome, you rock! Basically to sum it up the goal is to take the ability to grab traffic stats using the WDC and ensure that i can update daily to get the latest traffic info as well as retain already extracted older data so tableau could eventually report on traffic stats over months/years within tableau. - Essentially to use tableau(and this WDC) to get around githubs decision to only ever allow you to get the latest 14 days of stats.

**Comment by Etroid** [comment]
@jsevedge 

I've hacked together a solution that I believe will meet your needs for traffic stats.

The QA/dev environment - including the incremental refresh changes - can be tested here: https://github-web-data-connector-dev.herokuapp.com/github/

In the meanwhile I've published the previously released version to the more stable production environment: github-web-data-connector.herokuapp.com/github/

**Comment by jsevedge** [comment]
Hello @Etroid ,
      I tested against the dev environment and now do see the ability to do an incremental refresh, when i do it however it pulled in 0 rows...  I did a full refresh on the fifth and pulled in traffic stats for the past 14 days, but incremental refresh obviously pulling in 0 rows means that i am missing from the 5th up until now. If i do a full refresh it works but now i only have the last 14 days and lost the older data, should incremental refresh work as i am expecting or did i miss something?
Thanks,

**Comment by Etroid** [comment]
Hey @jsevedge ,

It was working for me. I'll do some more testing to figure out what may be causing the problem. Have you tried just doing an incremental refresh for a specific traffic stats object (e.g. clones, views)

**Comment by jsevedge** [comment]
@Etroid 
Hmm.. I have not.  I just tried to do incremental refresh on the whole data set with the assumption the end goal is that what I would want to do within Tableau server.

**Comment by Etroid** [comment]
@jsevedge 

I think I discovered the root of the issue. The repo table join was preventing the other tables from being updated because there were no new records detected. Give it another go using the development environment.

https://github-web-data-connector-dev.herokuapp.com/github/

**Comment by jsevedge** [comment]
@Etroid 

Ah ha, success!
