### ISSUE TITLE
Add missing identifiers to result set.

### ISSUE THREAD

**Issue by Etroid** [tableau-mkt/github-data-connector#3]
Github does not always attach all of the useful identifiers to its items. An example if when you look for all comments in a repository (e.g. repo1). It will not return that repository information, nor the issue/pull request it belongs to. That information is present in the 'url' property and can be extracted with some regex. However, some of that information is being passed in the API call url and can easily be attached.

**Comment by pvanoverbeek** [comment]
Closing - 3/23 ticket cleaning review
